### ISSUE TITLE
Need a bit of help using this

### ISSUE THREAD

**Issue by zackshapiro** [gre/gl-react-hue-rotate#2]
Hey Gaëtan,

Thanks so much for writing hue rotate. It's going to be hugely helpful in my project. I know you're working on a big re-write of react-gl right now so I appreciate you taking the time to read this issue.

I'm a bit confused as to how to use this, specifically what `children` should be.

I'm coming from using this in Framer, where you can essentially call `hueColor` and set it to a value of 0-360. 

I was hoping to do the same here, obviously the implementation is a bit different. 

Currently, I'm doing 

```
<HueRotate hue={Math.PI} >
    <MyElement />
</HueRotate>
```

...which doesn't seem to be quite right.

I'd love some guidance here. Ideally in my project I'll have a slider which will tap into HueRotate based on a 0-360 value.

Thanks!

**Comment by gre** [comment]
can you explain a bit more why "it doesn't seem to be quite right" ?

Here are 2 usage examples:

https://github.com/ProjectSeptemberInc/gl-react-dom/blob/master/Examples/Video/index.js#L24-L30

https://github.com/ProjectSeptemberInc/gl-react-native/blob/master/example/src/Simple/index.js#L156-L164

**Comment by zackshapiro** [comment]
Thanks for getting back to me and providing examples. I'm new to React so I was a bit confused about how to pass in the `children` prop. 

So if I were to provide the user a slider to manipulate the hue from 0 to 360, I guess I'd do something similar to what you're doing here: `<HueRotate hue={Math.PI * Math.cos(3 * time)}>`?  Where `time` is the slider value? Or would it just be `hue={slider.value}`

**Comment by gre** [comment]
in this implementation, `hue` is expected to be in radian. so it must be between 0 to 2*PI to make a full rotation.

so probably you would pass `slider.value * 2 * Math.PI` assuming the value move from 0 to 1 ?

or make your slider directly have 2*PI as max value

e.g.

```
<Slider maximumValue={2 * Math.PI}
```
